---
extends: [plugin:json-schema-validator/recommended]
ignorePatterns: ['!.github']
rules:
  jsonc/array-bracket-newline: [error, consistent]
  jsonc/array-bracket-spacing: error
  jsonc/comma-style: error
  jsonc/indent: [error, 2]
  jsonc/key-spacing: error
  jsonc/no-binary-numeric-literals: error
  jsonc/no-escape-sequence-in-identifier: error
  jsonc/no-hexadecimal-numeric-literals: error
  jsonc/no-infinity: error
  jsonc/no-nan: error
  jsonc/no-octal-escape: error
  jsonc/no-octal-numeric-literals: error
  jsonc/no-octal: error
  jsonc/no-plus-sign: error
  jsonc/no-unicode-codepoint-escapes: error
  jsonc/object-curly-newline: error
  jsonc/object-curly-spacing: error
  jsonc/object-property-newline: error
  json-schema-validator/no-invalid:
    - error
    - schemas:
        - fileMatch: [ci.yaml]
          schema: https://json.schemastore.org/github-workflow.json
        - fileMatch: [bitnami.json, comment.json, default.json, linuxserver.json]
          schema: https://docs.renovatebot.com/renovate-schema.json
overrides:
  - files: ['*.json']
    extends: ['plugin:jsonc/recommended-with-json']
  - files: ['*.json5']
    extends: ['plugin:jsonc/recommended-with-json5']
    rules:
      jsonc/comma-dangle: error
      jsonc/no-floating-decimal: error
      jsonc/no-multi-str: error
      jsonc/quote-props: [error, as-needed]
      jsonc/quotes: [error, single]
      jsonc/valid-json-number: error
